---
all:
  children:
    controllers:
      hosts:
        osc:
          ansible_host: 192.168.30.100
    computes:
      hosts:
        osn1:
          ansible_host: 192.168.30.101
  vars:
    ansible_user: root
#    ansible_become: true
    ansible_become_pass: cisco
    ansible_python_interpreter: /usr/bin/python3
#    ansible_ssh_pass: cisco
#    ansible_network_os: ios

